### ISSUE TITLE
Major bug 

### ISSUE THREAD

**Issue by ilijaNL** [advename/web-timing-safe-equal#1]
Hello, I just came across your library however looking at the code there is one major bug:

https://github.com/advename/web-timing-safe-equal/blob/0a4b98e63d5abc62c9a8e594643ec52479ca1249/src/webTimingSafeEqual.js#L73

You comparing the hmac of **leftUint8Array** against hmac of **leftUint8Array** which should be **rightUint8Array**

**Comment by advename** [comment]
Great find! It seems I accidentally copied and pasted the HMAC code within the `Promise.all` without making the necessary adjustments. Thank you for pointing that out!

**Comment by advename** [comment]
Fixed in [1.0.4 on npmjs](https://www.npmjs.com/package/@advena/web-timing-safe-equal) and in the github repo.

Thanks again @ilijaNL for taking your time inspecting the code and pointing it out.
